POST http://localhost:4004/odata/v4/support/Tickets
Content-Type: application/json

{
  "subject": "WiFi Not Working",
  "description": "<p>Office WiFi is not connecting</p>",
  "status": "N",
  "priority": "Medium",
  "category": "Network Issue",
  "subCategory": "WiFi",
  "assignedGroup": "Network Team"
}

###  
GET http://localhost:4004/support/Tickets
# Content-Type: application/json  

###
PUT http://localhost:4004/support/Tickets('c51ced8a-5b1d-4692-8159-7e18b89ef0f7')
Content-Type: application/json

{
  "status":"R"
}

###
POST http://localhost:4004/support/sendTicketMail
Content-Type: application/json

{
  "ticketNumber": "0001"
}

