### Create a new task
POST http://localhost:4004/odata/v4/tasklist/Tasklists
Content-Type: application/json
 
{
    "Description": "Sample Task-1",
    "AssignedTo": "John Doe",
    "Tags": "urgent,important",
    "Priority": "High",
    "Status": "Open",
    "StartDate": "2023-10-01",
    "EndDate": "2023-10-05",
    "ParentID": 0,
    "HierarchyLevel": 1,
    "DrillState": "collapsed",
    "Duration":0
    }